Repository fusionjs/fusion-plugin-font-loader-react, pull requests merged in 2018-10, with the labels that each got.

#117 Fix preload state leak
  src/plugin.js
  src/preload-session.js
Labels: bugfix

#118 Release v1.0.7
  package.json
Labels: release

#120 Update dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#122 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#125 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
