Repository fusionjs/fusion-plugin-font-loader-react, pull requests merged in 2018-08, with the labels that each got.

#95 Release v1.0.5-0
  package.json
Labels: release

#96 Update dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#98 Update documentation
  README.md
Labels: docs

#101 Update flow@0.79 and fix flow error
  package.json
  src/font-loader.js
  yarn.lock
Labels: greenkeeping

#105 Fix installation instructions in README
  README.md
Labels: docs

#107 Release v1.0.6
  package.json
Labels: release
