Repository fusionjs/fusion-plugin-font-loader-react, pull requests merged in 2018-11, with the labels that each got.

#130 Add `font-display: fallback` to font faces
  src/__tests__/fixtures/expected.js
  src/generate-font-faces.js
Labels: feature

#133 Upgrade deps
  package.json
  yarn.lock
Labels: greenkeeping

#134 Release v1.1.0
  package.json
Labels: release

#136 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
